name: release

on:
  push:
    branches:
      - "release/**"
    tags:
      - "v*"

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Setup JDK
        uses: actions/setup-java@v2.5.0
        with:
          distribution: temurin
          java-version: "17"

      - name: Decrypt
        run: bash ./release/decrypt-secrets.sh 
        env:
          ENCRYPT_KEY: ${{ secrets.ENCRYPT_KEY }}    

      - name: CHMOD
        run: chmod +x gradlew

      - name: Assemble APK
        run: bash ./gradlew -PKEY_ALIAS=$KEY_ALIAS -PKEY_PASSWORD=$KEY_PASSWORD -PSTORE_PASSWORD=$STORE_PASSWORD assembleRelease --stacktrace
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}


      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: tipjar/build/outputs/apk/release/tipjar-release.apk

  release:
    name: Release APK
    needs: apk
    runs-on: ubuntu-latest
    steps:
      - name: Download APK from build
        uses: actions/download-artifact@v1
        with:
          name: apk

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name}}
          
      - name: Upload Release APK
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: apk/tipjar-release.apk
          asset_name: ${{ github.event.repository.name }}.apk
          asset_content_type: application/zip